### ISSUE TITLE
Missing semi-colon after insert statement

### ISSUE THREAD

**Issue by marklit** [toddwschneider/nyc-taxi-data#10]
This line has a comma instead of a semi-colon at the end.

https://github.com/toddwschneider/nyc-taxi-data/blob/f25b8887ba84606ded0e11746952c796c8e33311/analysis/prepare_analysis.sql#L408

The issue manifests itself as:

```
ERROR:  syntax error at or near "CREATE"
LINE 23: CREATE INDEX index_custom_geoms ON custom_geometries USING g...
         ^
```

**Comment by toddwschneider** [comment]
fixed by https://github.com/toddwschneider/nyc-taxi-data/pull/12
