### ISSUE TITLE
Error in strsplit(unitspec, " ") : non-character argument

### ISSUE THREAD

**Issue by marklit** [toddwschneider/nyc-taxi-data#17]
After setting up the database I'm getting a non-character argument error when running the analysis.R script.

Setup steps:

```
cat raw_uber_data_urls.txt \
      raw_data_urls.txt | \
      xargs -n 1 -P 6 wget -P data/
./initialize_database.sh
./import_trip_data.sh
./import_uber_trip_data.sh
cat analysis/prepare_analysis.sql \
      tlc_statistics/create_statistics_tables.sql | \
      psql nyc-taxi-data
cd tlc_statistics
ruby import_statistics_data.rb # Patched as in #14
```

When running this:

``` bash
$ cat analysis.R | R --no-save
```

The following error occurs:

```
> png(filename = "graphs/citi_dropoffs.png", width = 640, height = 420)
> ggplot(data = filter(citi, dow %in% 1:5),
+        aes(x = timestamp_for_x_axis)) +
+   geom_histogram(binwidth = 600) +
+   scale_x_datetime("\ndrop off time", labels = date_format("%l %p"), minor_breaks = "1 hour") +
+   scale_y_continuous("taxi drop offs\n", labels = comma) +
+   title_with_subtitle("Citigroup Weekday Taxi Drop Offs at 388 Greenwich St", "Based on NYC TLC data from 1/2009–6/2015") +
+   theme_tws(base_size = 19)
Error in strsplit(unitspec, " ") : non-character argument
Calls: <Anonymous> ... fullseq.POSIXt -> seq -> floor_time -> parse_unit_spec -> strsplit
Execution halted
```

**Comment by toddwschneider** [comment]
@marklit thanks for reporting but I'm not sure I'm going to have time to look into this one anytime soon. In general I don't view `analysis.R` as a file that should be run in its entirety; I always ran it in bits and pieces. If you could say what's in the `citi` data frame that might help debug, otherwise I'm probably just going to let this one be for a while (feel free to comment out in your own local testing)

**Comment by marklit** [comment]
That's understandable. I'm about to use this script for some benchmarks so I'll comment out the 2 affected queries, the rest of it runs fine. When I next run the script I'll capture the value of `citi` and see if I can do more to find the root cause.

**Comment by toddwschneider** [comment]
Hi @marklit, I'm going to close this issue. As the repo and schema have evolved, I haven't really maintained the original analysis.R script to be perfectly consistent. I added a disclaimer to that effect here: https://github.com/toddwschneider/nyc-taxi-data/blob/master/analysis/analysis.R#L1-L9

(I also added a link to your benchmarks page from the README)
