### ISSUE TITLE
2015 Uber data decompressed to wrong folder

### ISSUE THREAD

**Issue by marklit** [toddwschneider/nyc-taxi-data#2]
The `import_uber_trip_data.sh` scripts intends to unzip `data/uber-raw-data-janjune-15.csv.zip` into the `data` directory but instead will extract it to the current working directory `import_uber_trip_data.sh` is executing from.

```bash
$ cd ~/nyc-taxi-data
$ ./import_uber_trip_data.sh
Tue Feb  9 14:25:18 EET 2016: beginning load for data/uber-raw-data-apr14.csv
...
cat: data/uber-raw-data-janjune-15.csv: No such file or directory
```

```bash
$ ls data/uber-raw-data-janjune-15.csv
ls: cannot access data/uber-raw-data-janjune-15.csv: No such file or directory

$ ls uber-raw-data-janjune-15.csv
uber-raw-data-janjune-15.csv
```

**Comment by toddwschneider** [comment]
thanks, fixed here: https://github.com/toddwschneider/nyc-taxi-data/commit/f7ebdd7c0b9604ef76959ef2f13dea7b1a990f67

**Comment by marklit** [comment]
Fantastic, thanks @toddwschneider.
