### ISSUE TITLE
What is the size of the raw data set?

### ISSUE THREAD

**Issue by amosbird** [toddwschneider/nyc-taxi-data#25]
I just finished downloading the nyc data set using `./download_raw_data.sh` . It's about 55GB. I wonder whether it's the correct size.

**Comment by toddwschneider** [comment]
@amosbird that sounds too small. In my experience it's something more in the neighborhood of 200GB. Can you check the list of files that you downloaded and compare to the list here: https://github.com/toddwschneider/nyc-taxi-data/blob/master/raw_data_urls.txt

There should be 161 files total

**Comment by amosbird** [comment]
Ok, thanks for the info. Yeah, I saw a bunch of incomplete data files.

**Comment by blacelle** [comment]
Given file has been moved to https://github.com/toddwschneider/nyc-taxi-data/blob/master/setup_files/raw_data_urls.txt
