### ISSUE TITLE
How to determine Airport Area?

### ISSUE THREAD

**Issue by jinwangjoshua** [toddwschneider/nyc-taxi-data#35]
Good work, may I ask how to determine the Latitude and longitude range of airports? How to determine the boundaries of rectangles?

**Comment by jinwangjoshua** [comment]
I am interested what is `dropoff_nyct2010_gid` in  prepare_analysis.sql?

**Comment by toddwschneider** [comment]
@jinwangjoshua I'd recommend using the `taxi_zones` shapefile, as it's available for all trips. It's referenced by `trips.pickup_location_id` and `trips.dropoff_location_id`. For example:

```sql
SELECT locationid, zone
FROM taxi_zones
WHERE zone IN ('Newark Airport', 'JFK Airport', 'LaGuardia Airport')
ORDER BY locationid;
```

```
 locationid |       zone        
------------+-------------------
          1 | Newark Airport
        132 | JFK Airport
        138 | LaGuardia Airport
(3 rows)
```
