### ISSUE TITLE
taxi_zone_centroids does not exist

### ISSUE THREAD

**Issue by ThomDietrich** [toddwschneider/nyc-taxi-data#37]
Hey Todd,
I followed the instructions given and the lines below fail with the following error. I am not sure if this is a local issue but I followed the import instructions and am not aware of errors.

https://github.com/toddwschneider/nyc-taxi-data/blob/6363ea98442a91452794e210a8c7c084070bdcd3/analysis/2017_update/queries_2017.sql#L50-L58

```
ERROR:  relation "taxi_zone_centroids" does not exist
LINE 7: FROM taxi_zone_centroids t, manhattan_centroid m;
```

Any idea what the cause of the issue might be? Thanks

**Comment by toddwschneider** [comment]
Ah looks like that table is created in a different file, sorry for the confusion

If you run the query in lines 1-6 here then you should be good to go:

https://github.com/toddwschneider/nyc-taxi-data/blob/f881215b0dfb3ff7613c96acf192823a412293c4/citibike_comparison/analysis/crosstown_queries.sql#L1-L6

**Comment by ThomDietrich** [comment]
Would you care for a PR to copy this part into nyc-taxi-data/analysis/2017_update/queries_2017.sql?

**Comment by toddwschneider** [comment]
Yes that's a fair point, I just added it here: https://github.com/toddwschneider/nyc-taxi-data/commit/23f757b318032129ecbc127be16b09fad0e1bce8, thanks again
