### ISSUE TITLE
[Info] - Reason for executing populate_yellow_trip for every file

### ISSUE THREAD

**Issue by murdockcrc** [toddwschneider/nyc-taxi-data#38]
Just wondering if there is a technical reason for this: why is the scrip `populate_yellow_trips` executed every ever data file after the `COPY` activity is finished? Wouldn't it be more efficient to have all the source files be imported into the db, and then execute the `populate` script? Thx for the clarification

**Comment by toddwschneider** [comment]
Hi, my primary motivation for running the script separately each on file is debugging. Especially when starting out, a bunch of the files have different schemas, and I'd get different errors depending on the file. I found that loading a single file at a time helped iterate through the errors faster.

I have not done any benchmarking of load performance doing one file at a time vs. multiple (or all) files simultaneously. It's possible that you might need a very powerful computer to load all in one shot, I'd imagine it puts a lot of strain on PostGIS, but I'm not sure as I haven't tried it.

I'm going to close this as an "issue", but let me know if more questions. Also let me know if you do any benchmarking! Thanks
