### ISSUE TITLE
Street related drop off data

### ISSUE THREAD

**Issue by bagherip** [toddwschneider/nyc-taxi-data#40]
I admire the job you have done there. I was just wondering how you generated results like
[THIS](https://github.com/toddwschneider/nyc-taxi-data/blob/master/analysis/graphs/murray_hill_bnt.png). The Data which is available on TLC database present only drop off and pick up data for each area but not the exact coordinates. i would be glad if you could explain that a bit more.

**Comment by toddwschneider** [comment]
Hi @bagherip, thanks!

The files before July 2016 included latitude/longitude coordinates for pickups and drop offs, but starting in July 2016 the files contain the zones for each trip, not precise coordinates. The image you linked to is based on data from the period when the TLC provided precise coordinates

I'm going to close this issue, hopefully that answers your questions but let me know if not. Thanks
