### ISSUE TITLE
alternative download script

### ISSUE THREAD

**Issue by ttw** [toddwschneider/nyc-taxi-data#44]
this is not very exciting but since I wrote it, I thought I'd share it and let you decide whether it'd be of any use.  very simple.  uses 'curl' instead 'wget' and compresses directly to disk using 'xz'.  it will also die on failures and allow transfers to resume (although that's probably not all that useful for many failures since it'll have to restart if 'xz' doesn't know what size the original data is).

[pull-data.sh.gz](https://github.com/toddwschneider/nyc-taxi-data/files/3759131/pull-data.sh.gz)

**Comment by toddwschneider** [comment]
Hi @ttw thanks, I appreciate the script, but I am going to close this as I don't think it's an "issue". If you wanted to start a wiki that might be more appropriate
