### ISSUE TITLE
Access method "brin" does not exist

### ISSUE THREAD

**Issue by saifrahmed** [toddwschneider/nyc-taxi-data#49]
After successfully running almost all of the script import_trip_data.sh I got an error on the final line:

`ERROR:  access method "brin" does not exist`

This appears to come from the final line: 
`
psql nyc-taxi-data -c "CREATE INDEX ON trips USING BRIN (pickup_datetime) WITH (pages_per_range = 32);"`

I tried BTREE instead of BRIN w/o luck. Any suggestions? Is the line required or optional for better performance?

**Comment by toddwschneider** [comment]
Hi @saifrahmed that line is not required, it just helps with performance, so you could delete it entirely if it's not working for you

What version of PostgreSQL are you using? BRIN indexes were added in v9.5, so if you're using 9.4 or earlier then that might be the issue?

**Comment by toddwschneider** [comment]
Closing this due to no response, feel free to re-open if any issues remain. Thanks
