### ISSUE TITLE
gzipped data

### ISSUE THREAD

**Issue by chappylol** [toddwschneider/nyc-taxi-data#5]
Not so much of an issue, but would it be possible to gzip the data at the download source? No biggie for me since it'll just download overnight, but it might affect others.

(Great project, btw. I just submitted a FOIA to Chicago for similar data. If they can give me a copy, would you want it? I have parking ticket/towing  data from last year if you're interested in that, too)

**Comment by toddwschneider** [comment]
This is an issue for the [NYC Taxi & Limousine Commission](http://www.nyc.gov/html/tlc/html/contact/contact.shtml), no? I think they would have to zip the data before posting it to their website, so you could try asking them...
