### ISSUE TITLE
Many years of S3 files fail to download

### ISSUE THREAD

**Issue by ryanbooz** [toddwschneider/nyc-taxi-data#53]
I'm attempting to update a copy of the Taxicab dataset and updated to the newest commits. When attempting to download just the Yellow/green data (I edited the URLs file), I'm only able to download 2009 and 2010 data. Both `wget` and a regular browser request fail for dozens of other URLs that I try from the file. I'm assuming the permissions in S3 got changed accidentally, but I wondered if there might be something else.

Example: https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2022-01.csv
Error: 404 not found (wget)

From S3:
```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>trip data/yellow_tripdata_2022-01.csv</Key>
<RequestId>BYPM9VSTW4FSM4EV</RequestId>
<HostId>/nQv/eDe2QprYThNg9mlGjozXlQ/7dX1Me4UNxtEkDG881eQV+IqbcbGIizpwazr9IRw7OOFN74=</HostId>
</Error>
```

Thanks for your work on this project and maintaining the dataset!

**Comment by toddwschneider** [comment]
Hi @ryanbooz, it looks like the TLC has completely changed the data files as of May 13, 2022: https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page

The new files are available in Parquet format. I will take a look in the coming weeks to figure out how to adapt this repo given the TLC's changes, but until then you'll have to look at TLC's page to figure out the best way to handle the new files. Thanks!

**Comment by ryanbooz** [comment]
🤦‍♂️ - I feel really silly for not noticing these links were coming from them. I actually had the thought while working on this that I was surprised you would keep hosting/serving these files just because. 😄 

Anyway, thanks for pointing it out. I'll see what we can do on this end. Many thanks!

**Comment by gogogo1024** [comment]
in setup_files/raw_data_urls.txt
1.  replace s3.amazonaws.com/nyc-tlc/trip+data  with  d37ci6vzurychx.cloudfront.net/trip-data
2. replace csv  with  parquet
solve this problem, anyone has better plan?

**Comment by toddwschneider** [comment]
@gogogo1024 yes, I still need to do some work to update this repo so that it imports parquet files instead of csv files. Thanks

**Comment by asad-awadia** [comment]
Getting a lot of ```403 Forbidden
2022-08-12 02:13:47 ERROR 403: Forbidden.``` when downloading raw data

**Comment by toddwschneider** [comment]
The repo is now updated to handle the new Parquet files. Here's the PR: https://github.com/toddwschneider/nyc-taxi-data/pull/54
