### ISSUE TITLE
Data size

### ISSUE THREAD

**Issue by LouisChang** [toddwschneider/nyc-taxi-data#7]
You said the data is around 260GB, but my computer storage is only 100GB..could you please tell me some hint to solve this problem?

Thank you!

**Comment by toddwschneider** [comment]
@LouisChang I don't think this belongs as an issue, so am closing. If you only have 100 GB of hard disk space available, here are some options:

1. Only download and process some of the taxi files (say, 2015 only)
2. Only download the Uber data files, as they're significantly smaller than the taxi data files
3. Buy an external hard drive
4. Use Google's BigQuery hosted version of the dataset: https://bigquery.cloud.google.com/table/imjasonh-storage:nyctaxi.trip_fare
