### ISSUE TITLE
April 2105 Green Taxi trip data fails to load

### ISSUE THREAD

**Issue by marklit** [toddwschneider/nyc-taxi-data#8]
While loading up the data into PostgreSQL I got the following error while the April 2014 data for Green Taxis was loading:

```
Sat Feb 27 22:56:15 EET 2016: beginning load for data/green_tripdata_2015-04.csv
ERROR:  extra data after last expected column
CONTEXT:  COPY green_tripdata_staging, line 2: "2,2015-04-01 00:00:00,2015-04-01 00:08:15,N,1,-73.958816528320312,40.716823577880859,-73.98297119140..."
Sat Feb 27 22:56:16 EET 2016: finished raw load for data/green_tripdata_2015-04.csv
```

It happened on the second line of the file and no data for that month for Green Taxis was loaded in.

Steps to re-create this:

This was all done on a fresh Ubuntu 14.04.3 LTS installation.

```bash
$ sudo apt-get install postgresql-9.3-postgis-2.1 git unzip
$ git clone https://github.com/toddwschneider/nyc-taxi-data.git
$ cd nyc-taxi-data
$ vi minimal_downloads.txt
```

Contents of `minimal_downloads.txt`:

```
https://storage.googleapis.com/tlc-trip-data/2015/green_tripdata_2014-04.csv
https://storage.googleapis.com/tlc-trip-data/2015/green_tripdata_2015-04.csv
https://storage.googleapis.com/tlc-trip-data/2015/yellow_tripdata_2014-04.csv
https://storage.googleapis.com/tlc-trip-data/2015/yellow_tripdata_2015-04.csv
```

```bash
$ cat minimal_downloads.txt | xargs -n 1 -P 6 wget -P data/ &
$ sudo su - postgres -c "psql -c 'CREATE USER mark; ALTER USER mark WITH SUPERUSER;'"
$ ./initialize_database.sh
$ ./import_trip_data.sh
```

**Comment by toddwschneider** [comment]
Whoops, I must have messed that up here: https://github.com/toddwschneider/nyc-taxi-data/commit/23972c0468283db8176773ca55ef1d38798f1876#diff-d6e35474f52f72d2e6cc6db85f0ce562R7 when I loaded the 2nd half of 2015 data. The TLC must have removed those extra `junk1` and `junk2` columns from the Jul-Dec files, but they're still in the Jan-Jun files. I will fix when I have a chance

**Comment by toddwschneider** [comment]
@marklit this should be fixed by this: https://github.com/toddwschneider/nyc-taxi-data/pull/9
